service: budgetr-frontend

image: nurey/budgetr-frontend

servers:
  web:
    hosts:
      - 38.49.217.106

# Use a different ssh user than root
ssh:
  user: ilia

# Configure builder setup.
builder:
  arch: amd64
  remote: ssh://ilia@optiplex
  local: false

registry:
  username: ilia@nurey.com

  # Always use an access token rather than real password when possible.
  password:
    - KAMAL_REGISTRY_PASSWORD

proxy:
  ssl: true
  host: budgetr-app.nurey.com
  app_port: 80

#healthcheck:
#  path: /
#  port: 80
